#!/usr/bin/env node
// Builds kit/icons.js: the icons the dashboard kit draws, as inline SVG markup.
// Source: the vendored Lucide set (vendor/lucide.min.js, ISC licence, see vendor/lucide-LICENSE).
// Add a name to ICONS and run `node scripts/kit-icons.cjs` to make another icon available to DK.icon().
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');

const ICONS = [
  // navigation and shell
  'layout-dashboard', 'files', 'list-checks', 'users', 'workflow', 'settings', 'home', 'building-2', 'folder', 'menu', 'search', 'bell', 'sun', 'moon', 'monitor', 'pin',
  // actions
  'plus', 'file-plus', 'download', 'upload', 'send', 'pencil', 'copy', 'trash-2', 'filter', 'ellipsis', 'external-link', 'link', 'x', 'check',
  // direction
  'chevron-right', 'chevron-down', 'arrow-right', 'arrow-up-right', 'reply',
  // status and time
  'info', 'circle-check', 'triangle-alert', 'clock', 'clock-alert', 'calendar', 'calendar-clock', 'history', 'lock', 'shield-check', 'eye',
  // content
  'file-text', 'search-check', 'stamp', 'message-square', 'inbox', 'user-round', 'key-round', 'kanban', 'rows-3', 'gauge', 'activity', 'target',
  // reference page
  'layers', 'blocks', 'type', 'grid', 'component', 'book-open', 'sparkles', 'code'
];

const src = fs.readFileSync(path.join(root, 'vendor/lucide.min.js'), 'utf8');
const start = src.indexOf('const icons=') + 'const icons='.length;
const end = src.indexOf('};', start) + 1;
const all = JSON.parse(src.slice(start, end));

const attr = v => String(v).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
const missing = ICONS.filter(n => !all[n]);
if (missing.length) { console.error('Not in vendor/lucide.min.js: ' + missing.join(', ')); process.exit(1); }
const out = {};
[...new Set(ICONS)].sort().forEach(name => {
  out[name] = all[name].map(([tag, a]) => `<${tag} ${Object.entries(a).map(([k, v]) => `${k}="${attr(v)}"`).join(' ')}/>`).join('');
});

const file = `/* Dashboard kit icons. Generated by scripts/kit-icons.cjs from the vendored Lucide set
 * (ISC licence, vendor/lucide-LICENSE). Do not edit by hand: add the name to the script and rebuild. */
window.DK_ICONS = ${JSON.stringify(out, null, 1)};
`;
fs.writeFileSync(path.join(root, 'kit/icons.js'), file);
console.log(`kit/icons.js: ${Object.keys(out).length} icons, ${(file.length / 1024).toFixed(1)} KB`);
